### PR TITLE
New versions and maintainer

### PR DESCRIPTION
**Pull request by FGarridoV**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by FGarridoV** [comment]
@conda-forge-admin, please rerender

**Comment by FGarridoV** [comment]
@moorepants Here is the second PR for biogeme

**Comment by moorepants** [comment]
This one was done correctly and a new build of biogeme is available which you can see here:

https://anaconda.org/conda-forge/biogeme/files

**Comment by moorepants** [comment]
I'm testing if the new build works with the TU Delft installer here: https://github.com/moorepants/anaconda-dee-config/pull/16

**Pull request merged**
